name: Rodar scraper diariamente

on:
  schedule:
    - cron: '0 15 * * *'  # 00:00 Brasília (UTC+0 = 03:00)
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Definir data de hoje e ontem
        id: data
        run: |
          echo "hoje=$(date +'%d/%m/%Y')" >> $GITHUB_OUTPUT
          echo "ontem=$(date -d 'yesterday' +'%d/%m/%Y')" >> $GITHUB_OUTPUT

      - name: Rodar o scraper
        run: |
          python main.py

      - name: Carregar variáveis de execução
        id: info_execucao
        run: |
          export VARIAVEIS=$(cat info_execucao.json)
          echo "data_inicial=$(jq -r '.data_inicial' info_execucao.json)" >> $GITHUB_OUTPUT
          echo "data_final=$(jq -r '.data_final' info_execucao.json)" >> $GITHUB_OUTPUT
          echo "qtd_resultados=$(jq -r '.qtd_resultados' info_execucao.json)" >> $GITHUB_OUTPUT
          echo "qtd_hcs=$(jq -r '.qtd_hcs' info_execucao.json)" >> $GITHUB_OUTPUT
          echo "paginas_total=$(jq -r '.paginas_total' info_execucao.json)" >> $GITHUB_OUTPUT
          echo "paginas_processadas=$(jq -r '.paginas_processadas' info_execucao.json)" >> $GITHUB_OUTPUT
          echo "horario_finalizacao=$(jq -r '.horario_finalizacao' info_execucao.json)" >> $GITHUB_OUTPUT

      - name: Verificar se há resultados
        id: verifica_arquivo
        run: |
          if ls hc_tjgo_*.xlsx 2>/dev/null; then
            echo "resultado=true" >> $GITHUB_OUTPUT
          else
            echo "resultado=false" >> $GITHUB_OUTPUT
          fi

      - name: Enviar e-mail com resultados (HCs encontrados)
        if: steps.verifica_arquivo.outputs.resultado == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USUARIO }}
          password: ${{ secrets.EMAIL_SENHA }}
          subject: "Relatório de HCs impetrados no STJ em ${{ steps.data.outputs.ontem }}"
          to: ${{ secrets.EMAIL_DESTINATARIO }}
          from: ${{ secrets.EMAIL_USUARIO }}
          body: |
            Prezado(a),

            Segue em anexo o relatório de Habeas Corpus (HCs) autuados no STJ, com origem no TJGO, na data de ${{ steps.data.outputs.ontem }}.
            Foram localizados ${{ steps.info_execucao.outputs.qtd_resultados }} resultados com base nos seguintes parâmetros de busca:
            Data inicial: ${{ steps.info_execucao.outputs.data_inicial }}
            Data final:  ${{ steps.info_execucao.outputs.data_final }}
            Tribunal de origem: TJGO
            Páginas com resultados: ${{ steps.info_execucao.outputs.paginas_total }}
            Páginas em que foi possível fazer a conferência: ${{ steps.info_execucao.outputs.paginas_processadas }}
            O script foi finalizado em: ${{ steps.info_execucao.outputs.horario_finalizacao }}

            Esta automação tem como objetivo auxiliar no acompanhamento processual, mas **não substitui a conferência manual nos canais oficiais do STJ**.

            Atenciosamente,
            Sistema automatizado - GitHub Actions
          attachments: hc_tjgo_*.xlsx

      - name: Enviar e-mail de ausência de resultados
        if: steps.verifica_arquivo.outputs.resultado == 'false'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USUARIO }}
          password: ${{ secrets.EMAIL_SENHA }}
          subject: "Nenhum HC impetrado no STJ em ${{ steps.data.outputs.ontem }}"
          to: ${{ secrets.EMAIL_DESTINATARIO }}
          from: ${{ secrets.EMAIL_USUARIO }}
          body: |
            Prezado(a),

            Nenhum Habeas Corpus com origem no TJGO foi autuado no STJ na data de ${{ steps.data.outputs.ontem }} com base nos seguintes parâmetros de busca:
            Data inicial: ${{ steps.info_execucao.outputs.data_inicial }}
            Data final:  ${{ steps.info_execucao.outputs.data_final }}
            Tribunal de origem: TJGO
            Páginas com resultados: ${{ steps.info_execucao.outputs.paginas_total }}
            Páginas em que foi possível fazer a conferência: ${{ steps.info_execucao.outputs.paginas_processadas }}
            O script foi finalizado em: ${{ steps.info_execucao.outputs.horario_finalizacao }}

            Esta automação tem como objetivo auxiliar no acompanhamento processual, mas **não substitui a conferência manual nos canais oficiais do STJ**.

            Atenciosamente,
            Sistema automatizado - GitHub Actions
